services:
  
  web: 
    build: .
    expose:
      - "5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis: 
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # This is the volume that will be created
      # /data is where data is stored in the redis image
      # in the redis service, we are mounting the volume redis-data to /data  
  nginx:
    image: "nginx:latest"
    ports: 
    - "5001:5001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web



volumes:
  redis-data: # This is the volume that will be created